-- AlterEnum
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'ENTC_PROJECT_EXPO';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'ENTC_DIGITAL_DANGAL';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'ENTC_SNAP_AND_SHINE';

